#!/bin/bash

OKGREEN='\033[92m'
OKBLUE='\033[94m'
ENDC='\033[0m'

set -e

echo "Initializing host setup service"
echo "Installing dependancies ..."
sudo apt update
xargs -a apt-packages.txt sudo apt install -y
echo -e "${OKGREEN} ✓ ${ENDC} complete"

echo "Configuring firewall for routing ssh requests ..."
sudo ufw allow ssh
echo -e "${OKGREEN} ✓ ${ENDC} complete"

ip=$(curl ifconfig.me)
user="$USER"
echo -e "Host Username: ${OKBLUE}$user${ENDC}"
echo -e "Public ip address: ${OKBLUE}$ip${ENDC}"