---
name: shellcheck
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  shell-lint:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install dependencies.
        run: |
        sudo apt update
        sudo apt install shellcheck -y

      - name: Run shellcheck linter.
        run: shellcheck client-setup host-setup